#############################################################################
#
# Copyright (c) 2010 Russell Sim <russell.sim@gmail.com> and Contributors.
# All Rights Reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################

# 600 - 699 - Object File I/O API calls
DATA_OBJ_CREATE_AN = 601
DATA_OBJ_OPEN_AN = 602
DATA_OBJ_PUT_AN = 606
DATA_PUT_AN = 607
DATA_OBJ_GET_AN = 608
DATA_GET_AN = 609
DATA_OBJ_REPL_AN = 610
DATA_COPY_AN = 611
DATA_OBJ_COPY_AN = 613
SIMPLE_QUERY_AN = 614
DATA_OBJ_UNLINK_AN = 615
COLL_CREATE_AN = 616  # 2.0.1
REG_DATA_OBJ_AN = 619
UNREG_DATA_OBJ_AN = 620
REG_REPLICA_AN = 621
MOD_DATA_OBJ_META_AN = 622
RULE_EXEC_SUBMIT_AN = 623
RULE_EXEC_DEL_AN = 624
EXEC_MY_RULE_AN = 625
OPR_COMPLETE_AN = 626
DATA_OBJ_RENAME_AN = 627
DATA_OBJ_RSYNC_AN = 628
DATA_OBJ_CHKSUM_AN = 629
PHY_PATH_REG_AN = 630
DATA_OBJ_PHYMV_AN = 631
DATA_OBJ_TRIM_AN = 632
OBJ_STAT_AN = 633
EXEC_CMD_AN = 634
SUB_STRUCT_FILE_CREATE_AN = 635
SUB_STRUCT_FILE_OPEN_AN = 636
SUB_STRUCT_FILE_READ_AN = 637
SUB_STRUCT_FILE_WRITE_AN = 638
SUB_STRUCT_FILE_CLOSE_AN = 639
SUB_STRUCT_FILE_UNLINK_AN = 640
SUB_STRUCT_FILE_STAT_AN = 641
SUB_STRUCT_FILE_FSTAT_AN = 642
SUB_STRUCT_FILE_LSEEK_AN = 643
SUB_STRUCT_FILE_RENAME_AN = 644
QUERY_SPEC_COLL_AN = 645
SUB_STRUCT_FILE_MKDIR_AN = 647
SUB_STRUCT_FILE_RMDIR_AN = 648
SUB_STRUCT_FILE_OPENDIR_AN = 649
SUB_STRUCT_FILE_READDIR_AN = 650
SUB_STRUCT_FILE_CLOSEDIR_AN = 651
DATA_OBJ_TRUNCATE_AN = 652
SUB_STRUCT_FILE_TRUNCATE_AN = 653
GET_XMSG_TICKET_AN = 654
SEND_XMSG_AN = 655
RCV_XMSG_AN = 656
SUB_STRUCT_FILE_GET_AN = 657
SUB_STRUCT_FILE_PUT_AN = 658
SYNC_MOUNTED_COLL_AN = 659
STRUCT_FILE_SYNC_AN = 660
CLOSE_COLLECTION_AN = 661
RM_COLL_AN = 663
STRUCT_FILE_EXTRACT_AN = 664
STRUCT_FILE_EXT_AND_REG_AN = 665
STRUCT_FILE_BUNDLE_AN = 666
CHK_OBJ_PERM_AND_STAT_AN = 667
GET_REMOTE_ZONE_RESC_AN = 668
DATA_OBJ_OPEN_AND_STAT_AN = 669
L3_FILE_GET_SINGLE_BUF_AN = 670
L3_FILE_PUT_SINGLE_BUF_AN = 671
DATA_OBJ_CREATE_AND_STAT_AN = 672
DATA_OBJ_CLOSE_AN = 673
DATA_OBJ_LSEEK_AN = 674
DATA_OBJ_READ_AN = 675
DATA_OBJ_WRITE_AN = 676
COLL_REPL_AN = 677
OPEN_COLLECTION_AN = 678
RM_COLL_AN21 = 679
MOD_COLL_AN = 680
COLL_CREATE_AN21 = 681
RM_COLL_OLD_AN = 682
REG_COLL_AN = 683
PHY_BUNDLE_COLL_AN = 684
UNBUN_AND_REG_PHY_BUNFILE_AN = 685

GET_MISC_SVR_INFO_AN = 700
GENERAL_ADMIN_AN = 701
GEN_QUERY_AN = 702
AUTH_REQUEST_AN = 703
AUTH_RESPONSE_AN = 704
AUTH_CHECK_AN = 705
MOD_AVU_METADATA_AN = 706
MOD_ACCESS_CONTROL_AN = 707
RULE_EXEC_MOD_AN = 708
GET_TEMP_PASSWORD_AN = 709
GENERAL_UPDATE_AN = 710
GSI_AUTH_REQUEST_AN = 711
READ_COLLECTION_AN = 713
USER_ADMIN_AN = 714
GENERAL_ROW_INSERT_AN = 715
GENERAL_ROW_PURGE_AN = 716
KRB_AUTH_REQUEST_AN = 717
